openapi: 3.0.1
info:
  title: 3Key RA Profiles Credential Provider Connector API
  description: REST APIs for implementations of custom Credential Provider
  contact:
    name: 3Key Company
    url: https://www.3key.company
    email: getinfo@3key.company
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v0.0.1
  x-logo:
    url: images/3keycompany.png
externalDocs:
  description: 3Key RA Profiles Documentation
  url: https://ra-profiles.3key.company
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Attributes API
  description: Connector Attributes API
- name: Info
  description: Connector Information API
paths:
  /v1/attributes/validate:
    post:
      tags:
      - Attributes API
      operationId: validateAttributes
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AttributeDefinition'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
  /v1:
    get:
      tags:
      - Info
      summary: List supported functions of the connector
      operationId: listSupportedFunctions
      responses:
        "404":
          description: Not found
        "200":
          description: Functions found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/EndpointDto'
        "400":
          description: Invalid request
  /v1/attributes:
    get:
      tags:
      - Attributes API
      operationId: listAttributeDefinitions
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttributeDefinition'
components:
  schemas:
    AttributeDefinition:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        required:
          type: boolean
        readOnly:
          type: boolean
        editable:
          type: boolean
        visible:
          type: boolean
        multiValue:
          type: boolean
        description:
          type: string
        validationRegex:
          type: string
        dependsOn:
          type: array
          items:
            $ref: '#/components/schemas/AttributeDependency'
        value:
          type: object
    AttributeDependency:
      type: object
      properties:
        name:
          type: string
        value:
          type: object
    EndpointDto:
      required:
      - context
      - id
      - method
      - name
      - required
      type: object
      properties:
        id:
          type: integer
          description: Id of the endpoint
          format: int64
          example: 123456
        name:
          type: string
          description: Name of the endpoint
          example: listSupportedFunctions
        context:
          type: string
          description: Context of the endpoint
          example: /v1
        method:
          type: string
          description: Method to be used for the endpoint
          example: POST
        required:
          type: boolean
          description: True if the endpoint is required for implementation
          example: true
