openapi: 3.0.1
info:
  title: CZERTAINLY Approvals API
  description: REST API for approvals in the platform
  contact:
    name: CZERTAINLY
    url: https://www.czertainly.com
    email: getinfo@czertainly.com
  license:
    name: MIT License
    url: https://github.com/3KeyCompany/CZERTAINLY/blob/develop/LICENSE.md
  version: 2.8.2-SNAPSHOT
  x-logo:
    url: images/czertainly_color_H.svg
externalDocs:
  description: CZERTAINLY Documentation
  url: https://docs.czertainly.com
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Approval profile Inventory
  description: Approval profile Inventory API
paths:
  /v1/approvalProfiles/{uuid}:
    get:
      tags:
      - Approval profile Inventory
      summary: Get Approval Profile Details
      operationId: getApprovalProfile
      parameters:
      - name: uuid
        in: path
        description: Approval profile UUID
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "200":
          description: Approval profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApprovalProfileDetailDto'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationServiceExceptionDto'
        "500":
          description: Internal Server Error
        "401":
          description: Unauthorized
    put:
      tags:
      - Approval profile Inventory
      summary: Edit an Approval profile
      operationId: editApprovalProfile
      parameters:
      - name: uuid
        in: path
        description: Approval profile UUID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApprovalProfileUpdateRequestDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "200":
          description: Approval profile updated
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationServiceExceptionDto'
        "500":
          description: Internal Server Error
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
              - Error Message 1
              - Error Message 2
        "401":
          description: Unauthorized
    delete:
      tags:
      - Approval profile Inventory
      summary: Delete an approval profile
      operationId: deleteApprovalProfile
      parameters:
      - name: uuid
        in: path
        description: Approval profile UUID
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Approval profile deleted
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationServiceExceptionDto'
        "500":
          description: Internal Server Error
        "401":
          description: Unauthorized
  /v1/approvalProfiles:
    get:
      tags:
      - Approval profile Inventory
      summary: List Approval Profiles
      operationId: listApprovalProfiles
      parameters:
      - name: paginationRequestDto
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/PaginationRequestDto'
      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationServiceExceptionDto'
        "500":
          description: Internal Server Error
        "401":
          description: Unauthorized
        "200":
          description: List of all the approval profiles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApprovalProfileResponseDto'
    post:
      tags:
      - Approval profile Inventory
      summary: Create a Approval profile
      operationId: createApprovalProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApprovalProfileRequestDto'
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "200":
          description: New Approval profile created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UuidDto'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationServiceExceptionDto'
        "500":
          description: Internal Server Error
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
              - Error Message 1
              - Error Message 2
        "401":
          description: Unauthorized
  /v1/approvalProfiles/{uuid}/enable:
    patch:
      tags:
      - Approval profile Inventory
      summary: Enabling of Approval profile
      operationId: enableApprovalProfile
      parameters:
      - name: uuid
        in: path
        description: Approval profile UUID
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthenticationServiceExceptionDto'
        "500":
          description: Internal Server Error
        "401":
          description: Unauthorized
        "204":
          description: Approval profile enabled
  /v1/approvalProfiles/{uuid}/disable:
    patch:
      tags:
      - Approval profile Inventory
      summary: Disabling of Approval profile
      operationId: disableApprovalProfile
      parameters:
      - name: uuid
        in: path
        description: Approval profile UUID
        required: true
        schema:
          type: string
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "204":
          description: Approval profile disabled
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorMessageDto'
        "403":
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthenticationServiceExceptionDto'
        "500":
          description: Internal Server Error
        "401":
          description: Unauthorized
components:
  schemas:
    ApprovalProfileUpdateRequestDto:
      required:
      - approvalSteps
      type: object
      properties:
        description:
          type: string
          description: Description of the Approval profile
          example: Detail description of the approval profile
        expiry:
          type: integer
          description: Expiration of the Approval profile in hours
          format: int32
          example: 30
        approvalSteps:
          type: array
          description: List of Approval steps for the Approval profile
          items:
            $ref: '#/components/schemas/ApprovalStepDto'
    ApprovalStepDto:
      required:
      - order
      type: object
      properties:
        userUuid:
          type: string
          description: Reference to responsible user to Approved the action
          format: uuid
        roleUuid:
          type: string
          description: Reference to responsible role of the users to Approved the
            action
          format: uuid
        groupUuid:
          type: string
          description: Reference to responsible group of the users to Approved the
            action
          format: uuid
        description:
          type: string
          description: Description of the Approval step
        order:
          type: integer
          description: Order of the position in the approval steps flow
          format: int32
        requiredApprovals:
          type: integer
          description: "Count of the required approvals for the Approval step, by\
            \ default there is 1 approval needed."
          format: int32
      description: List of Approval steps for the Approval profile
    ErrorMessageDto:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: Error message detail
          example: Error message
    AuthenticationServiceExceptionDto:
      required:
      - code
      - message
      - statusCode
      type: object
      properties:
        statusCode:
          type: integer
          description: Status code of the HTTP Request
          format: int32
        code:
          type: string
          description: Code of the result
        message:
          type: string
          description: Exception message
    ApprovalProfileRequestDto:
      required:
      - approvalSteps
      - enabled
      - name
      type: object
      properties:
        name:
          type: string
          description: Name of the Approval profile
          example: ApprovalProfile1
        description:
          type: string
          description: Description of the Approval profile
          example: Detail description of the approval profile
        enabled:
          type: boolean
          description: Enable of the Approval profile
          example: true
        expiry:
          type: integer
          description: Expiration of the Approval profile in hours
          format: int32
          example: 30
        approvalSteps:
          type: array
          description: List of Approval steps for the Approval profile
          items:
            $ref: '#/components/schemas/ApprovalStepDto'
    UuidDto:
      required:
      - uuid
      type: object
      properties:
        uuid:
          type: string
          description: Object identifier
    PaginationRequestDto:
      type: object
      properties:
        itemsPerPage:
          maximum: 1000
          type: integer
          description: Number of entries per page
          format: int32
          default: 10
        pageNumber:
          type: integer
          description: Page number for the request
          format: int32
          default: 1
    ApprovalProfileDto:
      required:
      - enabled
      - name
      - numberOfSteps
      - uuid
      - version
      type: object
      properties:
        uuid:
          type: string
          description: UUID of the Approval profile
        name:
          type: string
          description: Name of the Approval profile
          example: ApprovalProfile1
        version:
          type: integer
          description: Version of the Approval profile
          format: int32
          example: 1
        description:
          type: string
          description: Description of the Approval profile
          example: Detail description of the approval profile
        enabled:
          type: boolean
          description: Enable of the Approval profile
          example: true
        expiry:
          type: integer
          description: Expiration of the Approval profile in hours
          format: int32
          example: 30
        numberOfSteps:
          type: integer
          description: Number of the Approval profile steps
          format: int32
          example: 2
    ApprovalProfileResponseDto:
      required:
      - itemsPerPage
      - pageNumber
      - totalItems
      - totalPages
      type: object
      properties:
        itemsPerPage:
          type: integer
          description: Number of entries per page
          format: int32
        pageNumber:
          type: integer
          description: Page number for the request
          format: int32
        totalPages:
          type: integer
          description: Number of pages available
          format: int32
        totalItems:
          type: integer
          description: Number of items available
          format: int64
        approvalProfiles:
          type: array
          items:
            $ref: '#/components/schemas/ApprovalProfileDto'
    ApprovalProfileDetailDto:
      required:
      - approvalSteps
      - enabled
      - name
      - numberOfSteps
      - uuid
      - version
      type: object
      properties:
        uuid:
          type: string
          description: UUID of the Approval profile
        name:
          type: string
          description: Name of the Approval profile
          example: ApprovalProfile1
        version:
          type: integer
          description: Version of the Approval profile
          format: int32
          example: 1
        description:
          type: string
          description: Description of the Approval profile
          example: Detail description of the approval profile
        enabled:
          type: boolean
          description: Enable of the Approval profile
          example: true
        expiry:
          type: integer
          description: Expiration of the Approval profile in hours
          format: int32
          example: 30
        numberOfSteps:
          type: integer
          description: Number of the Approval profile steps
          format: int32
          example: 2
        approvalSteps:
          type: array
          description: List of Approval steps for the Approval profile
          items:
            $ref: '#/components/schemas/ApprovalStepDto'
