openapi: 3.0.1
info:
  title: 3Key RA Profiles CA Connector API
  description: REST APIs for implementations of custom CA Connector
  contact:
    name: 3Key Company
    url: https://www.3key.company
    email: getinfo@3key.company
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v0.0.1
externalDocs:
  description: 3Key RA Profiles Documentation
  url: https://ra-profiles.3key.company
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Attributes API
  description: Connector Attributes API
- name: Certification Authority API
  description: Certification Authority API
- name: Certificate Management API
  description: Certificate Management API
- name: End Entity Profiles API
  description: End Entity Profiles API
- name: Info
  description: Connector Information API
- name: End Entity Management API
  description: End Entity Management API
paths:
  /v1/authorities/{authorityId}/endEntityProfiles/{endEntityProfileName}/endEntities/{endEntityName}/resetPassword:
    put:
      tags:
      - End Entity Management API
      operationId: resetPassword
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: s
        in: path
        required: true
        schema:
          type: string
      - name: s1
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
  /v1/authorities:
    get:
      tags:
      - Certification Authority API
      operationId: listCAInstances
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CAInstanceDto'
    post:
      tags:
      - Certification Authority API
      operationId: createCAInstance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CAInstanceDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CAInstanceDto'
  /v1/authorities/{authorityId}:
    get:
      tags:
      - Certification Authority API
      operationId: getCAInstance
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CAInstanceDto'
    post:
      tags:
      - Certification Authority API
      operationId: updateCAInstance
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CAInstanceDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CAInstanceDto'
    delete:
      tags:
      - Certification Authority API
      operationId: removeCAInstance
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /v1/authorities/{authorityId}/endEntityProfiles/{endEntityProfileName}/endEntities:
    get:
      tags:
      - End Entity Management API
      operationId: listEndEntities
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: s
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EndEntityDto'
    post:
      tags:
      - End Entity Management API
      operationId: createEndEntity
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: s
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddEndEntityRequestDto'
        required: true
      responses:
        "200":
          description: OK
  /v1/authorities/{authorityId}/endEntityProfiles/{endEntityProfileName}/endEntities/{endEntityName}:
    get:
      tags:
      - End Entity Management API
      operationId: getEndEntity
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: s
        in: path
        required: true
        schema:
          type: string
      - name: s1
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EndEntityDto'
    post:
      tags:
      - End Entity Management API
      operationId: updateEndEntity
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: s
        in: path
        required: true
        schema:
          type: string
      - name: s1
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditEndEntityRequestDto'
        required: true
      responses:
        "200":
          description: OK
    delete:
      tags:
      - End Entity Management API
      operationId: removeEndEntity
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: s
        in: path
        required: true
        schema:
          type: string
      - name: s1
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
  /v1/authorities/{authorityId}/endEntityProfiles/{endEntityProfileName}/certificates/revoke:
    post:
      tags:
      - Certificate Management API
      operationId: revokeCertificate
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: s
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertRevocationDto'
        required: true
      responses:
        "200":
          description: OK
  /v1/authorities/{authorityId}/endEntityProfiles/{endEntityProfileName}/certificates/issue:
    post:
      tags:
      - Certificate Management API
      operationId: issueCertificate
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: s
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificateSignRequestDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CertificateSignResponseDto'
  /v1/attributes/validate:
    post:
      tags:
      - Attributes API
      operationId: validateAttributes
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AttributeDefinition'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
  /v1:
    get:
      tags:
      - Info
      summary: List supported functions of the connector
      operationId: listSupportedFunctions
      responses:
        "404":
          description: Not found
        "400":
          description: Invalid request
        "200":
          description: Functions found
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/EndpointDto'
  /v1/authorities/{authorityId}/endEntityProfiles:
    get:
      tags:
      - End Entity Profiles API
      summary: List available end entity profiles
      operationId: listEntityProfiles
      parameters:
      - name: authorityId
        in: path
        description: Authority Instance Id
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: End entities retrieved
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NameAndIdDTO'
        "404":
          description: Not found
        "400":
          description: Invalid request
  /v1/authorities/{authorityId}/endEntityProfiles/{endEntityProfileId}/certificateprofiles:
    get:
      tags:
      - End Entity Profiles API
      summary: List available certificate profiles for given end entity profile
      operationId: listCertificateProfiles
      parameters:
      - name: authorityId
        in: path
        description: Authority Instance Id
        required: true
        schema:
          type: integer
          format: int64
      - name: endEntityProfileId
        in: path
        description: End Entity Profile Id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Certificate profiles retrieved
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NameAndIdDTO'
        "404":
          description: Not found
        "400":
          description: Invalid request
  /v1/authorities/{authorityId}/endEntityProfiles/{endEntityProfileId}/cas:
    get:
      tags:
      - End Entity Profiles API
      summary: List available certification authorities for given end entity profile
      operationId: listCAsInProfile
      parameters:
      - name: authorityId
        in: path
        description: Authority Instance Id
        required: true
        schema:
          type: integer
          format: int64
      - name: endEntityProfileId
        in: path
        description: End Entity Profile Id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "404":
          description: Not found
        "400":
          description: Invalid request
        "200":
          description: CAs retrieved
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NameAndIdDTO'
  /v1/authorities/{authorityId}/connect:
    get:
      tags:
      - Certification Authority API
      operationId: getConnection
      parameters:
      - name: aLong
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
  /v1/attributes:
    get:
      tags:
      - Attributes API
      operationId: listAttributeDefinitions
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttributeDefinition'
components:
  schemas:
    AttributeDefinition:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        required:
          type: boolean
        readOnly:
          type: boolean
        editable:
          type: boolean
        visible:
          type: boolean
        multiValue:
          type: boolean
        description:
          type: string
        validationRegex:
          type: string
        dependsOn:
          type: array
          items:
            $ref: '#/components/schemas/AttributeDependency'
        value:
          type: object
    AttributeDependency:
      type: object
      properties:
        name:
          type: string
        value:
          type: object
    CAInstanceDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeDefinition'
        credential:
          $ref: '#/components/schemas/CredentialDto'
        status:
          type: string
        connectorId:
          type: integer
          format: int64
    CredentialDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        credentialType:
          type: string
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeDefinition'
        connectorId:
          type: integer
          format: int64
    AddEndEntityRequestDto:
      type: object
      properties:
        raProfile:
          $ref: '#/components/schemas/RaProfileDto'
        email:
          type: string
        extensionData:
          type: array
          items:
            $ref: '#/components/schemas/EndEntityExtendedInfoDto'
        password:
          type: string
        subjectAltName:
          type: string
        subjectDN:
          type: string
        username:
          type: string
    EndEntityExtendedInfoDto:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    RaProfileDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        caName:
          type: string
        certificateProfileName:
          type: string
        endEntityProfileName:
          type: string
        status:
          type: string
          enum:
          - NEW
          - ANY
        tokenType:
          type: string
          enum:
          - JKS
          - P12
          - PEM
          - USERGENERATED
        sendNotifications:
          type: boolean
        keyRecoverable:
          type: boolean
        enabled:
          type: boolean
    EditEndEntityRequestDto:
      type: object
      properties:
        raProfile:
          $ref: '#/components/schemas/RaProfileDto'
        email:
          type: string
        extensionData:
          type: array
          items:
            $ref: '#/components/schemas/EndEntityExtendedInfoDto'
        password:
          type: string
        subjectAltName:
          type: string
        subjectDN:
          type: string
        status:
          type: string
          enum:
          - NEW
          - FAILED
          - INITIALIZED
          - IN_PROCESS
          - GENERATED
          - REVOKED
          - HISTORICAL
          - KEY_RECOVERY
          - WAITING_FOR_ADD_APPROVAL
    CertRevocationDto:
      type: object
      properties:
        certificateSN:
          type: string
        issuerDN:
          type: string
        reason:
          type: string
          enum:
          - UNSPECIFIED
          - KEY_COMPROMISE
          - CA_COMPROMISE
          - AFFILIATION_CHANGED
          - SUPERSEDED
          - CESSATION_OF_OPERATION
          - CERTIFICATE_HOLD
          - REMOVE_FROM_CRL
          - PRIVILEGES_WITHDRAWN
          - AA_COMPROMISE
    CertificateSignRequestDto:
      type: object
      properties:
        password:
          type: string
        pkcs10:
          type: string
        username:
          type: string
    CertificateSignResponseDto:
      type: object
      properties:
        certificateData:
          type: string
    EndpointDto:
      required:
      - context
      - id
      - method
      - name
      - required
      type: object
      properties:
        id:
          type: integer
          description: Id of the endpoint
          format: int64
          example: 123456
        name:
          type: string
          description: Name of the endpoint
          example: listSupportedFunctions
        context:
          type: string
          description: Context of the endpoint
          example: /v1
        method:
          type: string
          description: Method to be used for the endpoint
          example: POST
        required:
          type: boolean
          description: True if the endpoint is required for implementation
          example: true
    NameAndIdDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    EndEntityDto:
      type: object
      properties:
        subjectDN:
          type: string
        email:
          type: string
        extensionData:
          type: array
          items:
            $ref: '#/components/schemas/EndEntityExtendedInfoDto'
        subjectAltName:
          type: string
        status:
          type: string
          enum:
          - NEW
          - FAILED
          - INITIALIZED
          - IN_PROCESS
          - GENERATED
          - REVOKED
          - HISTORICAL
          - KEY_RECOVERY
          - WAITING_FOR_ADD_APPROVAL
        username:
          type: string
